name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux,windows]
        arch: [amd64,arm]
    env:
      working-directory: ./12-multi-arch-deployments

    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Build the Docker image
      run: docker build --build-arg TARGETOS="${{ matrix.os }}" --build-arg TARGETARCH="${{ matrix.arch }}" --tag sahansera/hello-go:$(date +%s) --file Dockerfile .
      working-directory: ${{ env.working-directory }}
