name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./12-multi-arch-deployments

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sahansera/hello-go:$(date +%s)
      working-directory: ${{env.working-directory}}
